'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const read = (name) => fs.readFileSync(path.join(__dirname, '..', name), 'utf8')
const ui = read('ui-src/app.js')
test('批量确认说明开始先停服、会话中断、最后手动启动，不承诺无打断', () => {
  const body = ui.slice(ui.indexOf("title: '一键安装所有预装插件？'"), ui.indexOf("confirmText: '开始安装'"))
  assert.match(body, /安装前会先停止 DSH 服务/)
  assert.match(body, /进行中的会话会中断/)
  assert.match(body, /重新启动服务/)
  assert.doesNotMatch(read('README.md'), /变更不打断会话/)
})
test('手机连接开关在发命令前说明安装/卸载与重启，取消恢复勾选且不执行', () => {
  const start = ui.indexOf("$('pluginCards').addEventListener('change'")
  const body = ui.slice(start, ui.indexOf("$('btnPluginsRefresh')", start))
  assert.match(body, /id === 'bridge-next'/)
  assert.match(body, /会安装手机连接插件/)
  assert.match(body, /会卸载手机连接插件/)
  assert.match(body, /进行中的会话会中断/)
  assert.ok(body.indexOf('await confirmDialog') < body.indexOf("await cmd('pluginAction'"))
  assert.match(body, /if \(!ok\) \{ input\.checked = !turnOn; input\.disabled = false; return; \}/)
})
test('启动器更新失败保留重试入口和失败解释', () => {
  const update = read('ui-src/update.js')
  assert.match(update, /重试更新到/)
  assert.match(update, /更新已暂停/)
  assert.match(update, /note\.title = s\.error/)
})
